<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cover' => '封面',
    'Media ID' => '媒体ID',
    'Media UUID' => 'UUID',
    'Url' => '',
    'Resolution' => '分辨率',
    'Created At' => '创建时间',
    'Description' => '描述',
    'Duration' => '时长',
    'Format' => '媒体格式',
    'Fps' => '帧率',
    'Height' => '高',
    'Size' => '大小',
    'State' => '状态',
    'Title' => '标题',
    'Updated At' => '更新时间',
    'Width' => '宽',
];
