<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Wallet' => '创建钱包',
    'Delete Bankcard' => '删除银行卡',
    'Delete Wallet' => '删除钱包',
    'Manage Bankcard' => '银行卡管理',
    'Manage Wallet' => '钱包管理',
    'Update Bankcard' => '更新银行卡',
    'Update Wallet' => '更新钱包',
    'WalletLog Created At' => '',
    'WalletLog Msg' => '',
    'WalletLog Type' => '',
    'WalletLog Value' => '',
    'Withdrawals Notice' => '提现通知',
    'Withdrawals Rejected' => '提现拒绝',
    'Withdrawals has been confirmed' => '提现已经确认',
    'Withdrawals has been rejected' => '提现已经拒绝',
    'Amount' => '余额',
    'Are you sure you want to delete this item?' => '你确定要删除？',
    'Bank' => '银行',
    'Bank City' => '开户城市',
    'Bank Name' => '开户行',
    'Bank Username' => '开户名',
    'BankCard Number' => '卡号',
    'BankName' => '银行',
    'Bankcard' => '银行卡',
    'Bankcards' => '银行卡',
    'Batch Deletion' => '批量删除',
    'Clean' => '取消',
    'Create' => '创建',
    'Create Bankcard' => '添加卡',
    'Created At' => '创建时间',
    'Currency' => '币种',
    'Delete' => '删除',
    'Delete Withdrawals' => '删除提现',
    'Done' => '处理完成',
    'Insufficient money, please recharge.' => '余额不足，请先充值！',
    'Manage Withdrawals' => '提现管理',
    'Money' => '金额',
    'Operation' => '操作',
    'Pending' => '待处理',
    'Recharge' => '充值',
    'Rejected' => '已经拒绝',
    'Reset' => '重置',
    'Search' => '搜索',
    'Status' => '状态',
    'Submit' => '提交',
    'The minimum extraction of withdrawals {num}.' => '最少需要提现 {num}。',
    'Update' => '更新',
    'Update Bankcard: ' => '更新银行卡: ',
    'Update Withdrawals' => '更新提现',
    'Updated At' => '更新时间',
    'User Id' => '用户ID',
    'Wallet' => '钱包',
    'Wallet Manage' => '钱包管理',
    'Wallets' => '钱包',
    'Withdrawals' => '提现',
];
